### ISSUE TITLE
Rebuilding search index - error if search.field is inside a content block

### ISSUE THREAD

**Issue by thomasduenser** [sulu-io/sulu#1194] opened 2015-06-08 12:35 UTC
After I tried to rebuild the search index with following command:
```
app/console massive:search:index:rebuild
```

I've received this error multiple times:

```
Error indexing or de-indexing page (path: /cmf/webspace/contents/page, locale: de): Notice: Array to string conversion
```

Seems like the error comes from a property which has following tag but is **inside a block**:
```
<tag name="sulu.search.field" role="image"/>
```

After removing these lines, it was working again.

**Comment by dantleech** [comment] 2015-06-09 08:58
See also https://github.com/sulu-io/sulu/issues/1166

**Comment by dantleech** [comment] 2015-06-16 12:44
Cannot reproduce this.

Have:

1. Created a content type with a block
2. Placed a media in the block
3. Added the `sulu.search.field` tag with `role=image`
4. Rebuilt the index.

**Comment by dantleech** [comment] 2015-06-16 12:44
Can you supply a stack trace?

**Comment by danrot** [comment] 2015-06-18 13:10
@chirimoya How should we handle this issue if it can't be reproduced? Should we just close it, and reopen it if @thomasduenser stumbles upon it again?

**Comment by dantleech** [comment] 2015-06-18 13:14
I can now reproduce.

**Comment by dantleech** [comment] 2015-06-18 14:56
Basically, because of current limitations in the search indexing system, it is not possible to assign "role" attributes to `search.field` tags within blocks.

I have added an exception to hadle this [here](https://github.com/sulu-io/sulu/pull/1268/files#diff-0f5e72e095573a1b0d9d9f805cd9703bR234)

**Comment by danrot** [comment] 2015-06-25 08:27
@chirimoya Are you sure this can be marked as solved? I guess @dantleech forgot to add here that this occurs on any fields which can be multiplied (doesn't matter if it is in a multiplyable block or just the field on its own).

**Comment by chirimoya** [comment] 2015-06-25 08:46
The added exception will not solve this problem? /cc @dantleech

**Comment by danrot** [comment] 2015-06-25 09:20
This PR has not been merged, that's why I am asking. Not sure if this is already built into the refactoring.

**Comment by dantleech** [comment] 2015-06-25 12:52
MassiveSearchBundle does not currently support indexing arrays. I created this PR to at least throw an Exception: https://github.com/massiveart/MassiveSearchBundle/pull/54 (which can be merged btw).

Array support could be handled either here or in the MassiveSearchBundle.

**Comment by danrot** [comment] 2015-06-25 13:14
Reopened and linked this PR, will be closed as soon as it is merged.

**Closed** 2015-06-30 08:40 UTC
Labels: Bug

**Comment by danrot** [comment] 2015-06-30 08:41
This issue is solved by throwing this exception. It will tell you that it is not possible to have search fields on multiplied fields.
