### ISSUE TITLE
Exception thrown during preview template rendering after adding a navigation context

### ISSUE THREAD

**Issue by kriswillis** [sulu-io/sulu#1418] opened 2015-07-24 09:06 UTC
The following exception is intermittently thrown in the preview panel of the content editor after having added a navigation context and moving back to the Content tab.

> An exception has been thrown during the rendering of a template ("Document "Sulu\Bundle\ContentBundle\Document\PageDocument" with OID "000000007ab6546600007f638a81f666" is not managed, there are "5" managed objects,") in OSXWebsiteBundle:views:master.html.twig at line 27.

Line 27 in this instance is:

```php
{% include 'OSXWebsiteBundle:views:navigation.html.twig' 
    with { items: sulu_navigation_root_tree('header-lower', 1) } %}
```

### Steps to reproduce

1. Create new page as a child of another
2. Select "Published"
3. Enter template fields
4. Press Save
5. Go to Settings tab
6. Select a navigation context
7. Press save
8. Go to Content tab
9. Exception in preview panel

### Notes

@danrot mentioned the following on Slack:
> I have looked into it a bit deeper, and found that we are leaking some javascript events. Because of that we send way too many requests to the preview after the tab change, and this might be causing this behavior, although I am not quite sure.

**Comment by danrot** [comment] 2015-07-24 09:48
I have already had a look at this with @marcelmoosbrugger, and his refactoring won't fix this. The problem is that every tab is starting the main component (`@SuluContentBundle/Resources/public/component/content/main.js`) again, but the tabs do not navigate using the husky event, so the cleanup of husky is not executed, and therefore the are many instances of this component listening to this event.

If we fix this in some way, it would fix the multiple requests for the preview, but as already mentioned on slack, I am not sure if this will solve this specific problem. But I would say we fix this first, and dig into this issue deeper, if it still exists afterwards.

**Comment by danrot** [comment] 2015-10-08 05:39
@kriswillis I just wanted to fix this, but I am not able to reproduce this behavior following your given steps. Also there are no multiple requests anymore after switching the tabs for some time. So I am closing this issue, please reopen if you still have the same issue on the develop branch.

**Closed by danrot** 2015-10-08 05:39 UTC
Labels: Bug
