### ISSUE TITLE
Should not need to rename structure.dist files for Sulu to work after installation

### ISSUE THREAD

**Issue by dantleech** [sulu-io/sulu#953] opened 2015-03-30 08:10 UTC
It should not be necessary to copy the `.dist` files after installation, they should be copied in the same way that the `phpcr` and `parameters` files are copied after a composer install.

**Comment by danrot** [comment] 2015-03-30 09:04
But this should only be done for the default template.

**Comment by patkar** [comment] 2015-05-02 12:47
see #1056

**Comment by danrot** [comment] 2015-10-21 18:16
As @patkar already mentioned, this can be seen as duplicate of #1056, so I am going to close this one.

**Closed by danrot** 2015-10-21 18:16 UTC
Labels: Enhancement, Question
