### ISSUE TITLE
[ContentBundle] Error on URL generation for child of ghost page

### ISSUE THREAD

**Issue by sulu-io-user** [sulu-io/sulu#433] opened 2014-11-04 13:42 UTC
<a href="https://github.com/danrot"><img height="50" width="50" src="https://avatars.githubusercontent.com/u/405874?v=2" /></a>
By @danrot *from* https://github.com/sulu-cmf/SuluContentBundle/issues/152

After entering the title of a child of a ghostpage, you'll receive a 500-response, because it's not possible to load the URL of the ghostpage (since it doesn't have one).

**Comment by danrot** [comment] 2015-03-24 08:13
@berndhep What should happen if somebody creates a sub page in a localization, for which the parent page is a ghost page? Should that be possible at all? Currently the URL generation doesn't work then...

**Comment by danrot** [comment] 2015-03-24 08:31
After discussion with @berndhep, @chirimoya and @wachterjohannes we decided to skip the ghost pages for URL generation. But if the ghost page becomes a normal page, the URLs of the child have to be correctly updated.

**Comment by danrot** [comment] 2015-12-02 10:01
Duplicate of #1776

**Closed by danrot** 2015-12-02 10:01 UTC
Labels: Bug, duplicate
