### ISSUE TITLE
Backend search for snippets doesn't work

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#1329] opened 2015-07-02 13:04 UTC
Did the following things: 

1. Create a snippet template with following tag on title
  ```
 xml
  <tag name="sulu.search.field" role="title" />
  ```

2. Update CR database
  ```
  app/console sulu:webspaces:init
  ```

3. Create a new Snippet "Google" in Backend and publish it.

4. Search on the general backend search for "Google" have no result for the snippets

**Comment by danrot** [comment] 2015-07-02 13:43
I cannot reproduce that:
![image](https://cloud.githubusercontent.com/assets/405874/8478352/2073b7a4-20d1-11e5-9ed9-4a80194793f8.png)

**Comment by danrot** [comment] 2015-07-02 14:07
Seems to be an issue in an old version, fixed in the meantime, closing this issue.

**Closed by danrot** 2015-07-02 14:07 UTC
