### ISSUE TITLE
Error 500 copying Proxymanager to tmp

### ISSUE THREAD

**Issue by psren** [sulu-io/sulu#1464] opened 2015-08-07 19:46 UTC
I'm not quite sure if this is an issueor my fault.
I installed Sulu for the first time, following the docs.

Not I'm getting the following error if i call this page: ```https://sulu.cmf/admin/#content/contents/my_site/de```

```
{"message":"Warning: rename(\/tmp\/ProxyManagerGeneratedProxy__PM__SuluComponentDocumentManagerDocumentUnknownDocumentGenerateda84aebfffbf882fd8bddc950faa89e05.php.55c508a2865201.89209132,\/tmp\/ProxyManagerGeneratedProxy__PM__SuluComponentDocumentManagerDocumentUnknownDocumentGenerateda84aebfffbf882fd8bddc950faa89e05.php): Operation not permitted"
```

Do you have any idea?

Request
```
GET /admin/api/nodes?depth=1&webspace=wacg_de&language=de&exclude-ghosts=false HTTP/1.1
Host: sulu.cmf
Connection: keep-alive
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2475.0 Safari/537.36
Referer: https://sulu.cmf/admin/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
Cookie: PHPSESSID=qno2m23e4pu2h769086ajaidj6
```

Response headers
```
HTTP/1.1 500 Internal Server Error
Date: Fri, 07 Aug 2015 19:33:43 GMT
Server: Apache/2.4.12 (Ubuntu)
Cache-Control: no-cache
X-Debug-Token: 85f4ce
X-Debug-Token-Link: /admin/_profiler/85f4ce
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json
```

Here the full Stacktrace
```
{"error":{"code":500,"message":"Internal Server Error","exception":[{"message":"Warning: rename(\/tmp\/ProxyManagerGeneratedProxy__PM__SuluComponentDocumentManagerDocumentUnknownDocumentGenerateda84aebfffbf882fd8bddc950faa89e05.php.55c508a2865201.89209132,\/tmp\/ProxyManagerGeneratedProxy__PM__SuluComponentDocumentManagerDocumentUnknownDocumentGenerateda84aebfffbf882fd8bddc950faa89e05.php): Operation not permitted","class":"Symfony\\Component\\Debug\\Exception\\ContextErrorException","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/vendor\/ocramius\/proxy-manager\/src\/ProxyManager\/GeneratorStrategy\/FileWriterGeneratorStrategy.php","line":63,"args":[]},{"namespace":"Symfony\\Component\\Debug","short_class":"ErrorHandler","class":"Symfony\\Component\\Debug\\ErrorHandler","type":"->","function":"handleError","file":null,"line":null,"args":[["string","2"],["string","rename(\/tmp\/ProxyManagerGeneratedProxy__PM__SuluComponentDocumentManagerDocumentUnknownDocumentGenerateda84aebfffbf882fd8bddc950faa89e05.php.55c508a2865201.89209132,\/tmp\/ProxyManagerGeneratedProxy__PM__SuluComponentDocumentManagerDocumentUnknownDocumentGenerateda84aebfffbf882fd8bddc950faa89e05.php): Operation not permitted"],["string","\/var\/www\/vendor\/ocramius\/proxy-manager\/src\/ProxyManager\/GeneratorStrategy\/FileWriterGeneratorStrategy.php"],["string","63"],["array",{"classGenerator":["object","ProxyManager\\Generator\\ClassGenerator"],"className":["string","ProxyManagerGeneratedProxy\\__PM__\\Sulu\\Component\\DocumentManager\\Document\\UnknownDocument\\Generateda84aebfffbf882fd8bddc950faa89e05"],"generatedCode":["string","namespace ProxyManagerGeneratedProxy\\__PM__\\Sulu\\Component\\DocumentManager\\Document\\UnknownDocument;\n\nclass Generateda84aebfffbf882fd8bddc950faa89e05 extends \\Sulu\\Component\\DocumentManager\\Document\\UnknownDocument implements \\ProxyManager\\Proxy\\GhostObjectInterface\n{\n\n    \/**\n     * @var \\Closure|null initializer responsible for generating the wrapped object\n     *\/\n    private $initializer55c508a27dbd8742349881 = null;\n\n    \/**\n     * @var bool tracks initialization status - true while the object is initializing\n     *\/\n    private $initializationTracker55c508a27dd3f808306059 = false;\n\n    \/**\n     * @var bool[] map of public properties of the parent class\n     *\/\n    private static $publicProperties55c508a27cd6d019641117 = array(\n        \n    );\n\n    \/**\n     * @var mixed[] map of default property values of the parent class\n     *\/\n    private static $publicPropertiesDefaults55c508a27d785565033883 = array(\n        \n    );\n\n    private static $signaturea84aebfffbf882fd8bddc950faa89e05 = 'YTozOntzOjk6ImNsYXNzTmFtZSI7czo1NToiU3VsdVxDb21wb25lbnRcRG9jdW1lbnRNYW5hZ2VyXERvY3VtZW50XFVua25vd25Eb2N1bWVudCI7czo3OiJmYWN0b3J5IjtzOjQ0OiJQcm94eU1hbmFnZXJcRmFjdG9yeVxMYXp5TG9hZGluZ0dob3N0RmFjdG9yeSI7czoxOToicHJveHlNYW5hZ2VyVmVyc2lvbiI7czo1OiIxLjAuMCI7fQ==';\n\n    \/**\n     * {@inheritDoc}\n     *\/\n    public function getNodeName()\n    {\n        $this->initializer55c508a27dbd8742349881 && $this->callInitializer55c508a27e656629111041('getNodeName', array());\n\n        return parent::getNodeName();\n    }\n\n    \/**\n     * {@inheritDoc}\n     *\/\n    public function getUuid()\n    {\n        $this->initializer55c508a27dbd8742349881 && $this->callInitializer55c508a27e656629111041('getUuid', array());\n\n        return parent::getUuid();\n    }\n\n    \/**\n     * Triggers initialization logic for this ghost object\n     *\/\n    private function callInitializer55c508a27e656629111041($methodName, array $parameters)\n    {\n        if ($this->initializationTracker55c508a27dd3f808306059 || ! $this->initializer55c508a27dbd8742349881) {\n            return;\n        }\n\n        $this->initializationTracker55c508a27dd3f808306059 = true;\n\n        foreach (self::$publicPropertiesDefaults55c508a27d785565033883 as $key => $default) {\n            $this->$key = $default;\n        }\n\n        $this->initializer55c508a27dbd8742349881->__invoke($this, $methodName, $parameters, $this->initializer55c508a27dbd8742349881);\n\n        $this->initializationTracker55c508a27dd3f808306059 = false;\n    }\n\n    \/**\n     * @override constructor for lazy initialization\n     *\n     * @param \\Closure|null $initializer\n     *\/\n    public function __construct($initializer)\n    {\n        $this->initializer55c508a27dbd8742349881 = $initializer;\n    }\n\n    \/**\n     * @param string $name\n     *\/\n    public function & __get($name)\n    {\n        $this->initializer55c508a27dbd8742349881 && $this->callInitializer55c508a27e656629111041('__get', array('name' => $name));\n\n        $realInstanceReflection = new \\ReflectionClass(get_parent_class($this));\n\n        if (! $realInstanceReflection->hasProperty($name)) {\n            $targetObject = $this;\n\n            $backtrace = debug_backtrace(false);\n            trigger_error('Undefined property: ' . get_parent_class($this) . '::$' . $name . ' in ' . $backtrace[0]['file'] . ' on line ' . $backtrace[0]['line'], \\E_USER_NOTICE);\n            return $targetObject->$name;;\n            return;\n        }\n\n        $targetObject = unserialize(sprintf('O:%d:\"%s\":0:{}', strlen(get_parent_class($this)), get_parent_class($this)));\n        $accessor = function & () use ($targetObject, $name) {\n            return $targetObject->$name;\n        };\n            $backtrace = debug_backtrace(true);\n            $scopeObject = isset($backtrace[1]['object']) ? $backtrace[1]['object'] : new \\stdClass();\n            $accessor = $accessor->bindTo($scopeObject, get_class($scopeObject));\n        $returnValue = & $accessor();\n\n        return $returnValue;\n    }\n\n    \/**\n     * @param string $name\n     *\/\n    public function __set($name, $value)\n    {\n        $this->initializer55c508a27dbd8742349881 && $this->callInitializer55c508a27e656629111041('__set', array('name' => $name, 'value' => $value));\n\n        $realInstanceReflection = new \\ReflectionClass(get_parent_class($this));\n\n        if (! $realInstanceReflection->hasProperty($name)) {\n            $targetObject = $this;\n\n            return $targetObject->$name = $value;;\n            return;\n        }\n\n        $targetObject = unserialize(sprintf('O:%d:\"%s\":0:{}', strlen(get_parent_class($this)), get_parent_class($this)));\n        $accessor = function & () use ($targetObject, $name, $value) {\n            return $targetObject->$name = $value;\n        };\n            $backtrace = debug_backtrace(true);\n            $scopeObject = isset($backtrace[1]['object']) ? $backtrace[1]['object'] : new \\stdClass();\n            $accessor = $accessor->bindTo($scopeObject, get_class($scopeObject));\n        $returnValue = & $accessor();\n\n        return $returnValue;\n    }\n\n    \/**\n     * @param string $name\n     *\/\n    public function __isset($name)\n    {\n        $this->initializer55c508a27dbd8742349881 && $this->callInitializer55c508a27e656629111041('__isset', array('name' => $name));\n\n        $realInstanceReflection = new \\ReflectionClass(get_parent_class($this));\n\n        if (! $realInstanceReflection->hasProperty($name)) {\n            $targetObject = $this;\n\n            return isset($targetObject->$name);;\n            return;\n        }\n\n        $targetObject = unserialize(sprintf('O:%d:\"%s\":0:{}', strlen(get_parent_class($this)), get_parent_class($this)));\n        $accessor = function () use ($targetObject, $name) {\n            return isset($targetObject->$name);\n        };\n            $backtrace = debug_backtrace(true);\n            $scopeObject = isset($backtrace[1]['object']) ? $backtrace[1]['object'] : new \\stdClass();\n            $accessor = $accessor->bindTo($scopeObject, get_class($scopeObject));\n        $returnValue = $accessor();\n\n        return $returnValue;\n    }\n\n    \/**\n     * @param string $name\n     *\/\n    public function __unset($name)\n    {\n        $this->initializer55c508a27dbd8742349881 && $this->callInitializer55c508a27e656629111041('__unset', array('name' => $name));\n\n        $realInstanceReflection = new \\ReflectionClass(get_parent_class($this));\n\n        if (! $realInstanceReflection->hasProperty($name)) {\n            $targetObject = $this;\n\n            unset($targetObject->$name);;\n            return;\n        }\n\n        $targetObject = unserialize(sprintf('O:%d:\"%s\":0:{}', strlen(get_parent_class($this)), get_parent_class($this)));\n        $accessor = function () use ($targetObject, $name) {\n            unset($targetObject->$name);\n        };\n            $backtrace = debug_backtrace(true);\n            $scopeObject = isset($backtrace[1]['object']) ? $backtrace[1]['object'] : new \\stdClass();\n            $accessor = $accessor->bindTo($scopeObject, get_class($scopeObject));\n        $returnValue = $accessor();\n\n        return $returnValue;\n    }\n\n    public function __clone()\n    {\n        $this->initializer55c508a27dbd8742349881 && $this->callInitializer55c508a27e656629111041('__clone', array());\n    }\n\n    public function __sleep()\n    {\n        $this->initializer55c508a27dbd8742349881 && $this->callInitializer55c508a27e656629111041('__sleep', array());\n\n        return array_keys((array) $this);\n    }\n\n    \/**\n     * {@inheritDoc}\n     *\/\n    public function setProxyInitializer(\\Closure $initializer = null)\n    {\n        $this->initializer55c508a27dbd8742349881 = $initializer;\n    }\n\n    \/**\n     * {@inheritDoc}\n     *\/\n    public function getProxyInitializer()\n    {\n        return $this->initializer55c508a27dbd8742349881;\n    }\n\n    \/**\n     * {@inheritDoc}\n     *\/\n    public function initializeProxy()\n    {\n        return $this->initializer55c508a27dbd8742349881 && $this->callInitializer55c508a27e656629111041('initializeProxy', array());\n    }\n\n    \/**\n     * {@inheritDoc}\n     *\/\n    public function isProxyInitialized()\n    {\n        return ! $this->initializer55c508a27dbd8742349881;\n    }\n\n\n}\n"],"fileName":["string","\/tmp\/ProxyManagerGeneratedProxy__PM__SuluComponentDocumentManagerDocumentUnknownDocumentGenerateda84aebfffbf882fd8bddc950faa89e05.php"],"tmpFileName":["string","\/tmp\/ProxyManagerGeneratedProxy__PM__SuluComponentDocumentManagerDocumentUnknownDocumentGenerateda84aebfffbf882fd8bddc950faa89e05.php.55c508a2865201.89209132"]}]]},{"namespace":"","short_class":"","class":"","type":"","function":"rename","file":"\/var\/www\/vendor\/ocramius\/proxy-manager\/src\/ProxyManager\/GeneratorStrategy\/FileWriterGeneratorStrategy.php","line":63,"args":[["string","\/tmp\/ProxyManagerGeneratedProxy__PM__SuluComponentDocumentManagerDocumentUnknownDocumentGenerateda84aebfffbf882fd8bddc950faa89e05.php.55c508a2865201.89209132"],["string","\/tmp\/ProxyManagerGeneratedProxy__PM__SuluComponentDocumentManagerDocumentUnknownDocumentGenerateda84aebfffbf882fd8bddc950faa89e05.php"]]},{"namespace":"ProxyManager\\GeneratorStrategy","short_class":"FileWriterGeneratorStrategy","class":"ProxyManager\\GeneratorStrategy\\FileWriterGeneratorStrategy","type":"->","function":"generate","file":"\/var\/www\/vendor\/ocramius\/proxy-manager\/src\/ProxyManager\/Factory\/AbstractBaseFactory.php","line":109,"args":[["object","ProxyManager\\Generator\\ClassGenerator"]]},{"namespace":"ProxyManager\\Factory","short_class":"AbstractBaseFactory","class":"ProxyManager\\Factory\\AbstractBaseFactory","type":"->","function":"generateProxyClass","file":"\/var\/www\/vendor\/ocramius\/proxy-manager\/src\/ProxyManager\/Factory\/AbstractBaseFactory.php","line":76,"args":[["string","ProxyManagerGeneratedProxy\\__PM__\\Sulu\\Component\\DocumentManager\\Document\\UnknownDocument\\Generateda84aebfffbf882fd8bddc950faa89e05"],["string","Sulu\\Component\\DocumentManager\\Document\\UnknownDocument"],["array",{"className":["string","Sulu\\Component\\DocumentManager\\Document\\UnknownDocument"],"factory":["string","ProxyManager\\Factory\\LazyLoadingGhostFactory"],"proxyManagerVersion":["string","1.0.0"]}]]},{"namespace":"ProxyManager\\Factory","short_class":"AbstractBaseFactory","class":"ProxyManager\\Factory\\AbstractBaseFactory","type":"->","function":"generateProxy","file":"\/var\/www\/vendor\/ocramius\/proxy-manager\/src\/ProxyManager\/Factory\/AbstractLazyFactory.php","line":42,"args":[["string","Sulu\\Component\\DocumentManager\\Document\\UnknownDocument"]]},{"namespace":"ProxyManager\\Factory","short_class":"AbstractLazyFactory","class":"ProxyManager\\Factory\\AbstractLazyFactory","type":"->","function":"createProxy","file":"\/var\/www\/vendor\/sulu\/document-manager\/lib\/ProxyFactory.php","line":113,"args":[["string","Sulu\\Component\\DocumentManager\\Document\\UnknownDocument"],["object","Closure"]]},{"namespace":"Sulu\\Component\\DocumentManager","short_class":"ProxyFactory","class":"Sulu\\Component\\DocumentManager\\ProxyFactory","type":"->","function":"createProxyForNode","file":"\/var\/www\/vendor\/sulu\/document-manager\/lib\/Subscriber\/Behavior\/Mapping\/ParentSubscriber.php","line":164,"args":[["object","Sulu\\Bundle\\ContentBundle\\Document\\HomeDocument"],["object","Jackalope\\Node"]]},{"namespace":"Sulu\\Component\\DocumentManager\\Subscriber\\Behavior\\Mapping","short_class":"ParentSubscriber","class":"Sulu\\Component\\DocumentManager\\Subscriber\\Behavior\\Mapping\\ParentSubscriber","type":"->","function":"mapParent","file":"\/var\/www\/vendor\/sulu\/document-manager\/lib\/Subscriber\/Behavior\/Mapping\/ParentSubscriber.php","line":134,"args":[["object","Sulu\\Bundle\\ContentBundle\\Document\\HomeDocument"],["object","Jackalope\\Node"]]},{"namespace":"Sulu\\Component\\DocumentManager\\Subscriber\\Behavior\\Mapping","short_class":"ParentSubscriber","class":"Sulu\\Component\\DocumentManager\\Subscriber\\Behavior\\Mapping\\ParentSubscriber","type":"->","function":"handleHydrate","file":null,"line":null,"args":[["object","Sulu\\Component\\DocumentManager\\Event\\HydrateEvent"],["string","sulu_document_manager.hydrate"],["object","Sulu\\Component\\DocumentManager\\EventDispatcher\\DebugEventDispatcher"]]},{"namespace":"","short_class":"","class":"","type":"","function":"call_user_func","file":"\/var\/www\/vendor\/sulu\/document-manager\/lib\/EventDispatcher\/DebugEventDispatcher.php","line":63,"args":[["array",[["object","Sulu\\Component\\DocumentManager\\Subscriber\\Behavior\\Mapping\\ParentSubscriber"],["string","handleHydrate"]]],["object","Sulu\\Component\\DocumentManager\\Event\\HydrateEvent"],["string","sulu_document_manager.hydrate"],["object","Sulu\\Component\\DocumentManager\\EventDispatcher\\DebugEventDispatcher"]]},{"namespace":"Sulu\\Component\\DocumentManager\\EventDispatcher","short_class":"DebugEventDispatcher","class":"Sulu\\Component\\DocumentManager\\EventDispatcher\\DebugEventDispatcher","type":"->","function":"doDispatch","file":"\/var\/www\/app\/cache\/admin\/dev\/classes.php","line":1724,"args":[["array",[["array",[["object","Sulu\\Component\\DocumentManager\\Subscriber\\Core\\RegistratorSubscriber"],["string","handleDefaultLocale"]]],["array",[["object","Sulu\\Component\\DocumentManager\\Subscriber\\Core\\RegistratorSubscriber"],["string","handleDocumentFromRegistry"]]],["array",[["object","Sulu\\Component\\DocumentManager\\Subscriber\\Core\\RegistratorSubscriber"],["string","handleStopPropagationAndResetLocale"]]],["array",[["object","Sulu\\Component\\DocumentManager\\Subscriber\\Core\\InstantiatorSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\DocumentManager\\Subscriber\\Core\\RegistratorSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\Content\\Document\\Subscriber\\FallbackLocalizationSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\Content\\Document\\Subscriber\\ShadowLocaleSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\DocumentManager\\Subscriber\\Behavior\\Mapping\\LocaleSubscriber"],["string","handleLocale"]]],["array",[["object","Sulu\\Component\\Content\\Document\\Subscriber\\StructureSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\Content\\Document\\Subscriber\\NavigationContextSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\Content\\Document\\Subscriber\\RedirectTypeSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\Content\\Document\\Subscriber\\WorkflowStageSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\Content\\Document\\Subscriber\\OrderSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\Content\\Document\\Subscriber\\RouteSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\DocumentManager\\Subscriber\\Behavior\\Audit\\BlameSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\DocumentManager\\Subscriber\\Behavior\\Audit\\TimestampSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\DocumentManager\\Subscriber\\Behavior\\Mapping\\NodeNameSubscriber"],["string","handleNodeName"]]],["array",[["object","Sulu\\Component\\DocumentManager\\Subscriber\\Behavior\\Mapping\\UuidSubscriber"],["string","handleUuid"]]],["array",[["object","Sulu\\Component\\DocumentManager\\Subscriber\\Behavior\\Mapping\\ParentSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\DocumentManager\\Subscriber\\Behavior\\Mapping\\ChildrenSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\DocumentManager\\Subscriber\\Behavior\\Mapping\\PathSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\Content\\Document\\Subscriber\\ResourceSegmentSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\Content\\Document\\Subscriber\\TitleSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\Content\\Document\\Subscriber\\ExtensionSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\Content\\Document\\Subscriber\\WebspaceSubscriber"],["string","handleHydrate"]]],["array",[["object","Sulu\\Component\\DocumentManager\\Subscriber\\Core\\RegistratorSubscriber"],["string","handleEndHydrate"]]]]],["string","sulu_document_manager.hydrate"],["object","Sulu\\Component\\DocumentManager\\Event\\HydrateEvent"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"EventDispatcher","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","function":"dispatch","file":"\/var\/www\/app\/cache\/admin\/dev\/classes.php","line":1885,"args":[["string","sulu_document_manager.hydrate"],["object","Sulu\\Component\\DocumentManager\\Event\\HydrateEvent"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"ContainerAwareEventDispatcher","class":"Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher","type":"->","function":"dispatch","file":"\/var\/www\/vendor\/sulu\/document-manager\/lib\/Subscriber\/Phpcr\/FindSubscriber.php","line":95,"args":[["string","sulu_document_manager.hydrate"],["object","Sulu\\Component\\DocumentManager\\Event\\HydrateEvent"]]},{"namespace":"Sulu\\Component\\DocumentManager\\Subscriber\\Phpcr","short_class":"FindSubscriber","class":"Sulu\\Component\\DocumentManager\\Subscriber\\Phpcr\\FindSubscriber","type":"->","function":"handleFind","file":null,"line":null,"args":[["object","Sulu\\Component\\DocumentManager\\Event\\FindEvent"],["string","sulu_document_manager.find"],["object","Sulu\\Component\\DocumentManager\\EventDispatcher\\DebugEventDispatcher"]]},{"namespace":"","short_class":"","class":"","type":"","function":"call_user_func","file":"\/var\/www\/vendor\/sulu\/document-manager\/lib\/EventDispatcher\/DebugEventDispatcher.php","line":63,"args":[["array",[["object","Sulu\\Component\\DocumentManager\\Subscriber\\Phpcr\\FindSubscriber"],["string","handleFind"]]],["object","Sulu\\Component\\DocumentManager\\Event\\FindEvent"],["string","sulu_document_manager.find"],["object","Sulu\\Component\\DocumentManager\\EventDispatcher\\DebugEventDispatcher"]]},{"namespace":"Sulu\\Component\\DocumentManager\\EventDispatcher","short_class":"DebugEventDispatcher","class":"Sulu\\Component\\DocumentManager\\EventDispatcher\\DebugEventDispatcher","type":"->","function":"doDispatch","file":"\/var\/www\/app\/cache\/admin\/dev\/classes.php","line":1724,"args":[["array",[["array",[["object","Sulu\\Component\\DocumentManager\\Subscriber\\Phpcr\\FindSubscriber"],["string","handleFind"]]]]],["string","sulu_document_manager.find"],["object","Sulu\\Component\\DocumentManager\\Event\\FindEvent"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"EventDispatcher","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","function":"dispatch","file":"\/var\/www\/app\/cache\/admin\/dev\/classes.php","line":1885,"args":[["string","sulu_document_manager.find"],["object","Sulu\\Component\\DocumentManager\\Event\\FindEvent"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"ContainerAwareEventDispatcher","class":"Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher","type":"->","function":"dispatch","file":"\/var\/www\/vendor\/sulu\/document-manager\/lib\/DocumentManager.php","line":45,"args":[["string","sulu_document_manager.find"],["object","Sulu\\Component\\DocumentManager\\Event\\FindEvent"]]},{"namespace":"Sulu\\Component\\DocumentManager","short_class":"DocumentManager","class":"Sulu\\Component\\DocumentManager\\DocumentManager","type":"->","function":"find","file":"\/var\/www\/vendor\/sulu\/sulu\/src\/Sulu\/Component\/Content\/Mapper\/ContentMapper.php","line":826,"args":[["string","\/cmf\/wacg_de\/contents"],["string","de"],["array",{"load_ghost_content":["boolean",true]}]]},{"namespace":"Sulu\\Component\\Content\\Mapper","short_class":"ContentMapper","class":"Sulu\\Component\\Content\\Mapper\\ContentMapper","type":"->","function":"getContentDocument","file":"\/var\/www\/vendor\/sulu\/sulu\/src\/Sulu\/Component\/Content\/Mapper\/ContentMapper.php","line":359,"args":[["string","wacg_de"],["string","de"],["array",{"load_ghost_content":["boolean",true]}]]},{"namespace":"Sulu\\Component\\Content\\Mapper","short_class":"ContentMapper","class":"Sulu\\Component\\Content\\Mapper\\ContentMapper","type":"->","function":"loadByParent","file":"\/var\/www\/vendor\/sulu\/sulu\/src\/Sulu\/Bundle\/ContentBundle\/Repository\/NodeRepository.php","line":262,"args":[["null",null],["string","wacg_de"],["string","de"],["string","1"],["boolean",true],["boolean",false],["boolean",false]]},{"namespace":"Sulu\\Bundle\\ContentBundle\\Repository","short_class":"NodeRepository","class":"Sulu\\Bundle\\ContentBundle\\Repository\\NodeRepository","type":"->","function":"getNodes","file":"\/var\/www\/vendor\/sulu\/sulu\/src\/Sulu\/Bundle\/ContentBundle\/Controller\/NodeController.php","line":285,"args":[["null",null],["string","wacg_de"],["string","de"],["string","1"],["boolean",true],["boolean",false],["boolean",false]]},{"namespace":"Sulu\\Bundle\\ContentBundle\\Controller","short_class":"NodeController","class":"Sulu\\Bundle\\ContentBundle\\Controller\\NodeController","type":"->","function":"cgetAction","file":null,"line":null,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"]]},{"namespace":"","short_class":"","class":"","type":"","function":"call_user_func_array","file":"\/var\/www\/app\/bootstrap.php.cache","line":3054,"args":[["array",[["object","Sulu\\Bundle\\ContentBundle\\Controller\\NodeController"],["string","cgetAction"]]],["array",[["object","Symfony\\Component\\HttpFoundation\\Request"]]]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","function":"handleRaw","file":"\/var\/www\/app\/bootstrap.php.cache","line":3016,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["string","1"]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","function":"handle","file":"\/var\/www\/app\/bootstrap.php.cache","line":3165,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["string","1"],["boolean",true]]},{"namespace":"Symfony\\Component\\HttpKernel\\DependencyInjection","short_class":"ContainerAwareHttpKernel","class":"Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel","type":"->","function":"handle","file":"\/var\/www\/app\/bootstrap.php.cache","line":2406,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["string","1"],["boolean",true]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"Kernel","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->","function":"handle","file":"\/var\/www\/web\/admin.php","line":44,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"]]}]}]}}
```

**Comment by dantleech** [comment] 2015-08-08 17:12
This sounds like a permission issue, and could be caused by running the apache webserver and the console application as different users. Could you execute `chmod a+wrx /tmp/<the file>` and try your request again?

**Comment by danrot** [comment] 2015-08-11 07:27
Actually we should move the location of these files to somewhere in the `app/cache` directory, because the permissions would already be correct there.

**Comment by danrot** [comment] 2015-09-14 14:46
This will be fixed in the next hotfix release, which I will do today. Thank you for reporting.

**Closed** 2015-09-14 14:45 UTC
Labels: in progress
