### ISSUE TITLE
Admin Frontend Issues

### ISSUE THREAD

**Issue by turbo-ele** [sulu-io/sulu#1579] opened 2015-09-16 09:44 UTC
The following issues have been observed
Contact/Account in ContactExtensionBundle
* [x] Wrong space distribution when sidebar is activated and browser width is between 900px and 1090px
datagrid:  
<img width="1082" alt="bildschirmfoto 2015-09-17 um 11 32 40" src="https://cloud.githubusercontent.com/assets/5152633/9929873/dec9c294-5d2f-11e5-819c-aaffaa157757.png">

 
* [x] Styling of content, when sidebar overlaps content
<img width="941" alt="bildschirmfoto 2015-09-17 um 10 55 14" src="https://cloud.githubusercontent.com/assets/5152633/9929068/c1ae8dde-5d2a-11e5-9004-5865419d0c26.png">

* [x] nested table view: error when resizing browser
![image](https://cloud.githubusercontent.com/assets/5152633/9901465/393d3a62-5c68-11e5-9e84-c6cdaef1b111.png)

* [x] Resolution 1440px does not comply with sidebar. In fact, the navigation should be collapsed:
<img width="1402" alt="bildschirmfoto 2015-09-17 um 11 26 22" src="https://cloud.githubusercontent.com/assets/5152633/9929812/8038b226-5d2f-11e5-8563-9be0e1b1b70c.png">

**Comment by nnatter** [comment] 2015-09-18 14:31
problem 1,2 and 4 are caused by the inconsistent responsive-styling of the three-column-layout. this should be fixable by adapting the layout.scss of the adminbundle
(see https://github.com/sulu-io/sulu/issues/1600)

**Comment by nnatter** [comment] 2015-09-18 14:32
i was not able to reproduce problem 3 (nested table view: error when resizing browser). does this happen when a sidebar is shown?

**Comment by wachterjohannes** [comment] 2015-09-24 05:28
everything should be fixed ... @turbo-ele reopen if ´am wrong!

**Closed by wachterjohannes** 2015-09-24 05:28 UTC
Labels: Design
