### ISSUE TITLE
URL not generated again after template change on new Page

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#926] opened 2015-03-17 09:56 UTC
1. Create New Page
2. Set a Title (url will be generated)
3. Change Template (without saving)
4. Set Title again 
5. Url is not generated

![urlgeneration](https://cloud.githubusercontent.com/assets/1698337/6684724/3555ed7c-cc94-11e4-88ee-4d8f74b5b6a2.gif)

**Comment by danrot** [comment] 2015-03-18 08:12
You have already created an issue for that, so that's a duplicate of https://github.com/sulu-cmf/sulu-standard/issues/249

Closing the other issue, since it has to be fixed in this repository.

**Closed** 2015-10-07 13:50 UTC
Labels: Bug, in progress
