### ISSUE TITLE
Add a config parameter or something to add css files for the backend

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-io/sulu#1410] opened 2015-07-22 08:58 UTC
currently I think you can only add css file to the backend when you add it directly in your custom twig file which seems not a very good way to handle it.

**Comment by wachterjohannes** [comment] 2015-07-22 09:23
related with https://github.com/sulu-io/sulu/issues/417

**Comment by danrot** [comment] 2015-08-14 12:27
Closed as duplicate of #417

**Closed by danrot** 2015-08-14 12:27 UTC
Labels: duplicate, Enhancement
