### ISSUE TITLE
CK Editor Paste from Word Function

### ISSUE THREAD

**Issue by BettinaKaljo** [sulu-io/sulu#1095] opened 2015-05-15 13:46 UTC
Can't past text into overlay on IE 11

**Comment by alexander-schranz** [comment] 2015-06-02 09:49
can't reproduce

**Comment by danrot** [comment] 2015-06-05 11:12
@alexander-schranz Please clarify with @BettinaKaljo and close the issue, if it's really not reproduceable.

**Comment by berndhep** [comment] 2015-06-09 09:11
@BettinaKaljo Is this still relevant?

**Closed** 2015-07-01 11:22 UTC
Labels: Bug, ready
